export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR';

export const GET_PRODUCT_BY_CATEGORY = 'GET_PRODUCT_BY_CATEGORY';
export const GET_PRODUCT_BY_CATEGORY_SUCCESS =
  'GET_PRODUCT_BY_CATEGORY_SUCCESS';
export const GET_PRODUCT_BY_CATEGORY_ERROR = 'GET_PRODUCT_BY_CATEGORY_ERROR';

export const GET_PRODUCT_BY_RECOMMENT = 'GET_PRODUCT_BY_RECOMMENT';
export const GET_PRODUCT_BY_RECOMMENT_SUCCESS =
  'GET_PRODUCT_BY_RECOMMENT_SUCCESS';
export const GET_PRODUCT_BY_RECOMMENT_ERROR = 'GET_PRODUCT_BY_RECOMMENT_ERROR';
